one_shot/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.core.urlresolvers import reverse, reverse_lazy
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
	url(r'^$', "league_item_sets.views.index"),
	url(r'^user/', include('user_extension.urls', namespace='user')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('league_item_sets.ajax_urls', namespace='ajax'))
]

user_extension/urls.py
from django.conf.urls import include, url

from . import views

urlpatterns = [
	url(r'^$', "league_item_sets.views.index", name="home"),
	url(r'^login/?$', views.login, name='login'),
	url(r'^logout/?$', views.logout, name='logout'),
	url(r'^register/?$', views.register, name='register'),
	url(r'^itemsets/', include('league_item_sets.urls', namespace='itemsets')),
]

templates/layout.html
{% load static from staticfiles %}
{% load compress %}

<!doctype html>
<html>
<head>
  <title>{% block title %}{% endblock title %}</title>

  {% compress css %}
  <link rel="stylesheet" type="text/css" href="{%static 'css/normalize.css' %}">
  <link rel="stylesheet" type="text/css" href="{%static 'css/pure-release-0.6.0/pure-min.css' %}">
    <link rel="stylesheet" type="text/scss" href="{%static 'css/application.scss' %}">
  {% endcompress %}
</head>
<body>
  <div class="site-container">
    <nav>
      <a href="{% url 'user:itemsets:index' %}">Item Sets</a>
      {% if request.user.is_authenticated %}
        <form name='logout' action="{% url 'user:logout' %}" method="post" style="display:none;">{% csrf_token %}</form>
        <a href="javascript:document.forms['logout'].submit()">Logout</a>
      {% else %}
        <a href="{% url 'user:login' %}">Login</a>
        <a href="{% url 'user:register' %}">Register</a>
      {% endif %}
    </nav>
    {% block content %}{% endblock content %}
  </div>
  {% include "includes/load_statics.html" %}
</body>
</html>